name: C/C++ CI

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build-linux-unix:
    strategy:
      matrix:
        os: [ubuntu, macos]
        config: [Debug, Release]
    name: ${{matrix.os}}-${{matrix.config}}
    runs-on: ${{matrix.os}}-latest

    steps:
    - uses: actions/checkout@v2
    - name: CMake configure
      run: cmake -G "Unix Makefiles" -DSPLY_BUILD_UTILITIES=ON -DCMAKE_BUILD_TYPE=${{matrix.config}} .
    - name: Build
      run: cmake --build .

  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        architecture: [Win32, x64]
        config: [Debug, Release]
    name: windows-${{matrix.architecture}}-${{matrix.config}}
    
    steps:
    - uses: actions/checkout@v2
    - name: CMake configure
      run: cmake -DSPLY_BUILD_UTILITIES=ON -A ${{matrix.architecture}} .
    - name: Build
      run: cmake --build . --config ${{matrix.config}}
